/**
 * Application-wide constants and enums.
 */

const ROLES = {
  PATIENT: 'patient',
  HOSPITAL_ADMIN: 'hospital_admin',
  DOCTOR: 'doctor',
  ADMIN: 'admin',
};

const REPORT_TYPES = {
  BLOOD_TEST: 'blood_test',
  MRI: 'mri',
  CT_SCAN: 'ct_scan',
  XRAY: 'xray',
  ECG: 'ecg',
  ULTRASOUND: 'ultrasound',
  PATHOLOGY: 'pathology',
  OTHER: 'other',
};

const REPORT_STATUS = {
  ACTIVE: 'active',
  ARCHIVED: 'archived',
  DELETED: 'deleted',
};

const ACCESS_GRANT_STATUS = {
  ACTIVE: 'active',
  REVOKED: 'revoked',
  EXPIRED: 'expired',
  USED: 'used',
};

const ACCESS_SCOPE = {
  VIEW: 'view',
  DOWNLOAD: 'download',
};

const AUDIT_ACTIONS = {
  // Auth
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  PROFILE_UPDATED: 'PROFILE_UPDATED',

  // Hospital
  HOSPITAL_REGISTERED: 'HOSPITAL_REGISTERED',
  HOSPITAL_UPDATED: 'HOSPITAL_UPDATED',
  HOSPITAL_VERIFIED: 'HOSPITAL_VERIFIED',
  STAFF_ADDED: 'STAFF_ADDED',

  // Doctor
  DOCTOR_REGISTERED: 'DOCTOR_REGISTERED',
  DOCTOR_VERIFIED: 'DOCTOR_VERIFIED',

  // Patient Linking
  PATIENT_LINK_CREATED: 'PATIENT_LINK_CREATED',
  PATIENT_LINK_RESOLVED: 'PATIENT_LINK_RESOLVED',

  // Reports
  REPORT_UPLOADED: 'REPORT_UPLOADED',
  REPORT_VIEWED: 'REPORT_VIEWED',
  REPORT_DOWNLOADED: 'REPORT_DOWNLOADED',
  REPORT_DELETED: 'REPORT_DELETED',

  // Access
  ACCESS_GRANT_CREATED: 'ACCESS_GRANT_CREATED',
  ACCESS_GRANT_REVOKED: 'ACCESS_GRANT_REVOKED',
  ACCESS_TOKEN_VALIDATED: 'ACCESS_TOKEN_VALIDATED',
  ACCESS_DENIED: 'ACCESS_DENIED',

  // Signatures
  SIGNATURE_VERIFIED: 'SIGNATURE_VERIFIED',
  SIGNATURE_FAILED: 'SIGNATURE_FAILED',
};

const AUDIT_RESULTS = {
  SUCCESS: 'success',
  FAILURE: 'failure',
  DENIED: 'denied',
};

// Patient linking code config
const LINKING_CODE_LENGTH = 8;
const LINKING_CODE_EXPIRY_MINUTES = 5;

// Access token config
const ACCESS_TOKEN_LENGTH = 48;
const DEFAULT_ACCESS_EXPIRY_HOURS = 24;

module.exports = {
  ROLES,
  REPORT_TYPES,
  REPORT_STATUS,
  ACCESS_GRANT_STATUS,
  ACCESS_SCOPE,
  AUDIT_ACTIONS,
  AUDIT_RESULTS,
  LINKING_CODE_LENGTH,
  LINKING_CODE_EXPIRY_MINUTES,
  ACCESS_TOKEN_LENGTH,
  DEFAULT_ACCESS_EXPIRY_HOURS,
};
